spring.application.name=Portafolio-Api
server.port=${API_PORT:3000}

app.github.personal=${APP_GITHUB_PERSONAL:}
app.github.organizations=${APP_GITHUB_ORGANIZATIONS:}
app.github.excluded-repositories=${APP_GITHUB_EXCLUDED_REPOSITORIES:}
app.github.token=${APP_GITHUB_TOKEN:}
app.github.base-url=${APP_GITHUB_BASE_URL:https://api.github.com}

spring.jpa.open-in-view=false

app.reniew.projects.time=${APP_RENIEW_PROJECTS_TIME:6}
app.reniew.certs.time=${APP_RENIEW_CERTS_TIME:6}
app.refresh-on-startup=${APP_REFRESH_ON_STARTUP:true}

app.certificates.base-url=${APP_CERTIFICATES_BASE_URL:}
app.redis.certs.time=${APP_REDIS_CERTS_TIME:24}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DATABASE:portafolio-api}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:ejemplo}
spring.datasource.password=${DATABASE_PASSWORD:ejemplo}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=always
spring.data.redis.host=${REDIS:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:cacheable}
logging.level.org.springframework.mail=INFO
logging.level.es.joseluisgs.tienda.services.email=INFO